nodeLinker: node-modules
nmHoistingLimits: "workspaces"
npmRegistries:
  "https://proscia-583366545747.d.codeartifact.us-east-1.amazonaws.com/npm/development/":
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"
npmRegistryServer: "https://proscia-583366545747.d.codeartifact.us-east-1.amazonaws.com/npm/development/"
yarnPath: .yarn/releases/yarn-3.2.4.cjs